// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using realEstate.DATA;
using System;

namespace realEstate.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    partial class RealEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("realEstate.Models.RealEstateModel", b =>
                {
                    b.Property<int>("RealEstateModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AC");

                    b.Property<string>("Adress");

                    b.Property<string>("City");

                    b.Property<string>("Description");

                    b.Property<string>("Elevator");

                    b.Property<int>("Floor");

                    b.Property<string>("Image1");

                    b.Property<string>("Image2");

                    b.Property<int>("Meters");

                    b.Property<int>("Parking");

                    b.Property<int>("Price");

                    b.Property<string>("PropertyStatus");

                    b.Property<int>("Rooms");

                    b.Property<string>("image3");

                    b.HasKey("RealEstateModelId");

                    b.ToTable("realEstateModels");
                });

            modelBuilder.Entity("realEstate.Models.SellingAgent", b =>
                {
                    b.Property<int>("SellingAgentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgentPhoto");

                    b.Property<string>("SellingAgentName");

                    b.HasKey("SellingAgentId");

                    b.ToTable("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
